//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projet_dot_net.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Pupils
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pupils()
        {
            this.Results = new HashSet<Results>();
        }

        public System.Guid Id { get; set; }
        [Display(Name = "Nom")]
        [Required(ErrorMessage = "the FirstName is required")]
        public string FirstName { get; set; }
        [Display(Name = "Prénom")]
        [Required(ErrorMessage = "the LastName is required")]
        public string LastName { get; set; }
        [Display(Name = "Sexe")]
        [Required(ErrorMessage = "the Sex is required")]
        public short Sex { get; set; }
        [Display(Name = "Année de naissance")]
        [Required(ErrorMessage = "the BirthdayDate is required")]
        [DataType(DataType.Date)]
        public System.DateTime BirthdayDate { get; set; }
        [Display(Name = "Etat")]
        [Required(ErrorMessage = "the State is required")]
        public short State { get; set; }
        [Display(Name = "Tuteur")]
        [Required(ErrorMessage = "the Tutor is required")]
        public System.Guid Tutor_Id { get; set; }
        [Display(Name = "Classe")]
        [Required(ErrorMessage = "the Classroom is required")]
        public System.Guid Classroom_Id { get; set; }
        [Display(Name = "Niveau")]
        [Required(ErrorMessage = "the Level is required")]
        public System.Guid Level_Id { get; set; }

        public virtual Classrooms Classrooms { get; set; }
        public virtual Levels Levels { get; set; }
        public virtual Tutors Tutors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Results> Results { get; set; }
    }
}